services:
  # app-prod имя контейнера
  app-prod:
    build:
      # путь до Dockerfile
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mock-json:
    image: "ajoelpod/mock-json-server"
    volumes:
      - ./data.json:/usr/src/app/data.json
    ports:
      - 8000:8000
