services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  mock-json:
    image: "ajoelpod/mock-json-server"
    volumes:
      - ./data.json:/usr/src/app/data.json
    ports:
      - 8000:8000
